services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
        - REACT_APP_FEISHU_APP_ID=${REACT_APP_FEISHU_APP_ID}
        - REACT_APP_FEISHU_APP_SECRET=${REACT_APP_FEISHU_APP_SECRET}
        - REACT_APP_FEISHU_REDIRECT_URI=${REACT_APP_FEISHU_REDIRECT_URI}
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
        - REACT_APP_API_SECRET_KEY=${REACT_APP_API_SECRET_KEY}
        - REACT_APP_ADMIN_IDS=${REACT_APP_ADMIN_IDS}
        - REACT_APP_ADMIN_OPEN_IDS=${REACT_APP_ADMIN_OPEN_IDS}
        - REACT_APP_APP_NAME=${REACT_APP_APP_NAME}
        - REACT_APP_VERSION=${REACT_APP_VERSION}
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - FEISHU_APP_ID=${FEISHU_APP_ID}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
      - FEISHU_TENANT_ACCESS_TOKEN=${FEISHU_TENANT_ACCESS_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server/logs:/app/logs
      - ./output:/app/output
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
  output: